//
// Created by annanagi on 02.03.18.
//

#ifndef JIMP_EXERCISES_DOUBLEBASEPALINDROMES_H
#define JIMP_EXERCISES_DOUBLEBASEPALINDROMES_H


class DoubleBasePalindromes {

};


#endif //JIMP_EXERCISES_DOUBLEBASEPALINDROMES_H
